- name: "5.1  | PATCH | Ensure 'Enable guest mode in browser' is set to 'Disabled'"
  ansible.windows.win_regedit:
      path: HKLM:\SOFTWARE\Policies\Google\Chrome
      name: BrowserGuestModeEnabled
      data: 0
      type: dword
  when:
      - win19cis_rule_9_1_1
  tags:
      - level1
      - rule_5.1

- name: "5.2  | PATCH | Ensure 'Incognito mode availability ' is set to 'Enabled: Incognito mode disabled'"
  ansible.windows.win_regedit:
      path: HKLM:\SOFTWARE\Policies\Google\Chrome
      name: IncognitoModeAvailability
      data: 1
      type: dword
  when:
      - win19cis_rule_9_1_1
  tags:
      - level1
      - rule_5.2

- name: "5.3  | PATCH | Ensure 'Set disk cache size, in bytes' is set to 'Enabled: 250609664'"
  ansible.windows.win_regedit:
      path: HKLM:\SOFTWARE\Policies\Google\Chrome
      name: DiskCacheSize
      data: 0x0ef00000
      type: dword
  when:
      - win19cis_rule_9_1_1
  tags:
      - level1
      - rule_5.3