---
- name: "1.1.1 | PATCH | Ensure 'Cross-origin HTTP Authentication prompts' is set to 'Disabled'"
  ansible.windows.win_regedit:
      path: HKLM:\SOFTWARE\Policies\Google\Chrome
      name: AllowCrossOriginAuthPrompt
      data: 0
      type: dword
  when:
      - win19cis_rule_9_1_1
  tags:
      - level1
      - rule_1.1.1  

- name: "1.2.1 | PATCH | Ensure 'Configure the list of domains on which Safe Browsing will not trigger warnings' is set to 'Disabled'"
  ansible.windows.win_regedit:
      path: HKLM:\SOFTWARE\Policies\Google\Chrome
      name: SafeBrowsingAllowlistDomains
      data: 0
      type: dword
  when:
      - win19cis_rule_9_1_1
  tags:
      - level1
      - rule_1.2.1

- name: "1.2.2 | PATCH | Ensure 'Safe Browsing Protection Level' is set to 'Enabled: Standard Protection' or higher"
  ansible.windows.win_regedit:
      path: HKLM:\SOFTWARE\Policies\Google\Chrome
      name: SafeBrowsingProtectionLevel
      data: 1
      type: dword
  when:
      - win19cis_rule_9_1_1
  tags:
      - level1
      - rule_1.2.2

- name: "1.3 | PATCH | Ensure 'Allow Google Cast to connect to Cast devices on all IP addresses' is set to 'Disabled'"
  ansible.windows.win_regedit:
      path: HKLM:\SOFTWARE\Policies\Google\Chrome
      name: MediaRouterCastAllowAllIPs
      data: 0
      type: dword
  when:
      - win19cis_rule_9_1_1
  tags:
      - level1
      - rule_1.3

- name: "1.4 | PATCH | Ensure 'Allow queries to a Google time service' is set to 'Enabled'"
  ansible.windows.win_regedit:
      path: HKLM:\SOFTWARE\Policies\Google\Chrome
      name: BrowserNetworkTimeQueriesEnabled
      data: 1
      type: dword
  when:
      - win19cis_rule_9_1_1
  tags:
      - level1
      - rule_1.4


- name: "1.5 | PATCH | Ensure 'Allow the audio sandbox to run' is set to 'Enabled'"
  ansible.windows.win_regedit:
      path: HKLM:\SOFTWARE\Policies\Google\Chrome
      name: AudioSandboxEnabled
      data: 1
      type: dword
  when:
      - win19cis_rule_9_1_1
  tags:
      - level1
      - rule_1.5

- name: "1.6 | PATCH | Ensure 'Ask where to save each file before downloading' is set to 'Enabled'"
  ansible.windows.win_regedit:
      path: HKLM:\SOFTWARE\Policies\Google\Chrome
      name: PromptForDownloadLocation
      data: 1
      type: dword
  when:
      - win19cis_rule_9_1_1
  tags:
      - level1
      - rule_1.6

- name: "1.7 | PATCH | Ensure 'Continue running background apps when Google Chrome is closed' is set to 'Disabled'"
  ansible.windows.win_regedit:
      path: HKLM:\SOFTWARE\Policies\Google\Chrome
      name: BackgroundModeEnabled
      data: 0
      type: dword
  when:
      - win19cis_rule_9_1_1
  tags:
      - level1
      - rule_1.6

- name: "1.8 | PATCH | Ensure 'Control SafeSites adult content filtering' is set to 'Enabled: Filter top level sites (but not embedded iframes) for adult content' specified"
  ansible.windows.win_regedit:
      path: HKLM:\SOFTWARE\Policies\Google\Chrome
      name: SafeSitesFilterBehavior
      data: 0
      type: dword
  when:
      - win19cis_rule_9_1_1
  tags:
      - level1
      - rule_1.8

- name: "1.9 | PATCH | Ensure 'Determine the availability of variations' is set to 'Disabled'"
  ansible.windows.win_regedit:
      path: HKLM:\SOFTWARE\Policies\Google\Chrome
      name: ChromeVariations
      data: 0
      type: dword
  when:
      - win19cis_rule_9_1_1
  tags:
      - level1
      - rule_1.9

- name: "1.10 | PATCH | Ensure 'Disable Certificate Transparency enforcement for a list of Legacy Certificate Authorities' is set to 'Disabled'"
  ansible.windows.win_regedit:
      path: HKLM:\SOFTWARE\Policies\Google\Chrome
      name: CertificateTransparencyEnforcementDisabledForLegacyCas
      state: absent
  when:
      - win19cis_rule_9_1_1
  tags:
      - level1
      - rule_1.10

- name: "1.11 | PATCH | Ensure 'Disable Certificate Transparency enforcement for a list of subjectPublicKeyInfo hashes' is set to 'Disabled'"
  ansible.windows.win_regedit:
      path: HKLM:\SOFTWARE\Policies\Google\Chrome
      name: CertificateTransparencyEnforcementDisabledForCas
      state: absent
  when:
      - win19cis_rule_9_1_1
  tags:
      - level1
      - rule_1.11

- name: "1.12 | PATCH | Ensure 'Disable Certificate Transparency enforcement for a list of URLs' is set to 'Disabled'"
  ansible.windows.win_regedit:
      path: HKLM:\SOFTWARE\Policies\Google\Chrome
      name: CertificateTransparencyEnforcementDisabledForUrls
      state: absent
  when:
      - win19cis_rule_9_1_1
  tags:
      - level1
      - rule_1.12

- name: "1.13 | PATCH | Ensure 'Disable saving browser history' is set to 'Disabled'"
  ansible.windows.win_regedit:
      path: HKLM:\SOFTWARE\Policies\Google\Chrome
      name: SavingBrowserHistoryDisabled
      data: 0
      type: dword
  when:
      - win19cis_rule_9_1_1
  tags:
      - level1
      - rule_1.13

- name: "1.14 | PATCH | Ensure 'DNS interception checks enabled' is set to 'Enabled'"
  ansible.windows.win_regedit:
      path: HKLM:\SOFTWARE\Policies\Google\Chrome
      name: DNSInterceptionChecksEnabled
      data: 1
      type: dword
  when:
      - win19cis_rule_9_1_1
  tags:
      - level1
      - rule_1.14

- name: "1.15 | PATCH | Ensure 'Enable component updates in Google Chrome' is set to 'Enabled'"
  ansible.windows.win_regedit:
      path: HKLM:\SOFTWARE\Policies\Google\Chrome
      name: ComponentUpdatesEnabled
      data: 1
      type: dword
  when:
      - win19cis_rule_9_1_1
  tags:
      - level1
      - rule_1.15

- name: "1.17 | PATCH | Ensure 'Enable online OCSP/CRL checks' is set to 'Disabled'"
  ansible.windows.win_regedit:
      path: HKLM:\SOFTWARE\Policies\Google\Chrome
      name: EnableOnlineRevocationChecks
      data: 0
      type: dword
  when:
      - win19cis_rule_9_1_1
  tags:
      - level1
      - rule_1.17

- name: "1.18 | PATCH | Ensure 'Enable Renderer Code Integrity' is set to 'Enabled'"
  ansible.windows.win_regedit:
      path: HKLM:\SOFTWARE\Policies\Google\Chrome
      name: RendererCodeIntegrityEnabled
      data: 1
      type: dword
  when:
      - win19cis_rule_9_1_1
  tags:
      - level1
      - rule_1.18

- name: "1.19 | PATCH | Ensure 'Enable security warnings for command-line flags' is set to 'Enabled'"
  ansible.windows.win_regedit:
      path: HKLM:\SOFTWARE\Policies\Google\Chrome
      name: CommandLineFlagSecurityWarningsEnabled
      data: 1
      type: dword
  when:
      - win19cis_rule_9_1_1
  tags:
      - level1
      - rule_1.19

- name: "1.20 | PATCH | Ensure 'Enable third party software injection blocking' is set to 'Enabled'"
  ansible.windows.win_regedit:
      path: HKLM:\SOFTWARE\Policies\Google\Chrome
      name: ThirdPartyBlockingEnabled
      data: 1
      type: dword
  when:
      - win19cis_rule_9_1_1
  tags:
      - level1
      - rule_1.20

- name: "1.21 | PATCH | Ensure 'Enables managed extensions to use the Enterprise Hardware Platform API' is set to 'Disabled'"
  ansible.windows.win_regedit:
      path: HKLM:\SOFTWARE\Policies\Google\Chrome
      name: EnterpriseHardwarePlatformAPIEnabled
      data: 1
      type: dword
  when:
      - win19cis_rule_9_1_1
  tags:
      - level1
      - rule_1.21

- name: "1.22 | PATCH | Ensure 'Ephemeral profile' is set to 'Disabled'"
  ansible.windows.win_regedit:
      path: HKLM:\SOFTWARE\Policies\Google\Chrome
      name: ForceEphemeralProfiles
      data: 0
      type: dword
  when:
      - win19cis_rule_9_1_1
  tags:
      - level1
      - rule_1.22

- name: "1.23 | PATCH | Ensure 'Import autofill form data from default browser on first run' is set to 'Disabled'"
  ansible.windows.win_regedit:
      path: HKLM:\SOFTWARE\Policies\Google\Chrome
      name: ImportAutofillFormData
      data: 0
      type: dword
  when:
      - win19cis_rule_9_1_1
  tags:
      - level1
      - rule_1.23

- name: "1.24 | PATCH | Ensure 'Import of homepage from default browser on first run' is set to 'Disabled'"
  ansible.windows.win_regedit:
      path: HKLM:\SOFTWARE\Policies\Google\Chrome
      name: ImportHomepage
      data: 0
      type: dword
  when:
      - win19cis_rule_9_1_1
  tags:
      - level1
      - rule_1.24

- name: "1.25 | PATCH | Ensure 'Import search engines from default browser on first run' is set to 'Disabled'"
  ansible.windows.win_regedit:
      path: HKLM:\SOFTWARE\Policies\Google\Chrome
      name: ImportSearchEngine
      data: 0
      type: dword
  when:
      - win19cis_rule_9_1_1
  tags:
      - level1
      - rule_1.25

- name: "1.26 | PATCH | Ensure 'List of names that will bypass the HSTS policy check' is set to 'Disabled'"
  ansible.windows.win_regedit:
      path: HKLM:\SOFTWARE\Policies\Google\Chrome
      name: HSTSPolicyBypassList
      state: absent
  when:
      - win19cis_rule_9_1_1
  tags:
      - level1
      - rule_1.26

- name: "1.27 | PATCH | Ensure 'Origins or hostname patterns for which restrictions on insecure origins should not apply' is set to 'Disabled'"
  ansible.windows.win_regedit:
      path: HKLM:\SOFTWARE\Policies\Google\Chrome
      name: OverrideSecurityRestrictionsOnInsecureOrigin
      data: 0
      type: dword
  when:
      - win19cis_rule_9_1_1
  tags:
      - level1
      - rule_1.27

- name: "1.28 | PATCH | Ensure 'Suppress lookalike domain warnings on domains' is set to 'Disabled'"
  ansible.windows.win_regedit:
      path: HKLM:\SOFTWARE\Policies\Google\Chrome
      name: LookalikeWarningAllowlistDomains
      data: 0
      type: dword
  when:
      - win19cis_rule_9_1_1
  tags:
      - level1
      - rule_1.27

- name: "1.29 | PATCH | Ensure 'Suppress the unsupported OS warning' is set to 'Disabled'"
  ansible.windows.win_regedit:
      path: HKLM:\SOFTWARE\Policies\Google\Chrome
      name: WebRtcLocalIpsAllowedUrls
      state: absent
  when:
      - win19cis_rule_9_1_1
  tags:
      - level1
      - rule_1.29

- name: "1.30 | PATCH | Ensure 'URLs for which local IPs are exposed in WebRTC ICE candidates' is set to 'Disabled'"
  ansible.windows.win_regedit:
      path: HKLM:\SOFTWARE\Policies\Google\Chrome
      name: WebRtcLocalIpsAllowedUrls
      state: absent
  when:
      - win19cis_rule_9_1_1
  tags:
      - level1
      - rule_1.30
